# Generated by Django 5.2.13 on 2026-04-16 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PRE-SURVEY-NOT-COMPLETED', 'Pre-survey Not Completed'), ('PRE-SURVEY-COMPLETED', 'Pre-survey Completed'), ('EXPERIMENT', 'Experiment'), ('POST-SURVEY-NOT-COMPLETED', 'Post-survey Not Completed'), ('POST-SURVEY-COMPLETED', 'Post-survey Completed'), ('COMPLETED', 'Completed'), ('GAVE_UP', 'Gave Up')], default='ENROLLED', max_length=30)),
                ('group', models.CharField(choices=[('CONTROL', 'Control'), ('TREATMENT', 'Treatment'), ('UNASSIGNED', 'Unassigned')], default='UNASSIGNED', max_length=20)),
            ],
        ),
    ]
