"""
Django settings for bear_backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jdcg58jxe#_z_r3!nc6w5l*4g3@0)xp&$ay$&u62$eby(e%jc3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    # Necessario per le WebSockets. è il server ASGI (Asincrono) usato da Django Channels le WebSocket.
    'daphne',    

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # DRF (Django REST Framework)
    'rest_framework',

    # per abbattere i muri CORS aggiungiamo 'corsheaders' tra le app installate e il relativo middleware (vedi sotto)
    # questo ci permette di accettare richieste da domini diversi (es. frontend in localhost:3000 e backend in localhost:8000)
    # inoltre aggiungiamo la nostra app "api" che conterrà tutte le views e modelli
    'corsheaders',

    # Necessario per le WebSockets. Serve a gestire i canali di comunicazione webSockets
    'channels',

    'api',         
]

MIDDLEWARE = [

    # Middleware per gestire i CORS (Cross-Origin Resource Sharing), necessario per permettere al frontend di comunicare 
    # con il backend se sono su domini/porte diverse
    'corsheaders.middleware.CorsMiddleware',

    # questi sotto sono tutti quelli di default gia installati da Django
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bear_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# EDIT: Commentiamo WSGI siccome è un Server SINCRONO e non supporta le WebSockets
# Attiviamo invece ASGI che è un Server ASINCRONO e supporta le WebSockets (vedi asgi.py)

#WSGI_APPLICATION = 'bear_backend.wsgi.application'
ASGI_APPLICATION = 'bear_backend.asgi.application'

# Configuriamo il Channel Layer 
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DEBUG: Sblocca tutte le chiamate esterne (Solo per Sviluppo!)
CORS_ALLOW_ALL_ORIGINS = True

# Aggiungiamo 
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.dev']